[package]
name = "atsame70_xpro"
version = "0.4.6"
edition = "2021"
authors = [
    "Viktor Sonesten <viktor.sonesten@grepit.se>"
]
license = "MIT OR Apache-2.0"

[dependencies]
cortex-m-rtic = "1.1.4"
cortex-m = "0.7"
panic-halt = "0.2"
panic-rtt-target = { version = "0.1.2", features = ["cortex-m"] }
rtt-target = { version = "0.3.1", features = ["cortex-m"], optional = true }
usb-device = "0.3.2"
usbd-serial = "0.2.0"
heapless = "0.7"
log = { version = "0.4", default-features = false, optional = true }

[dependencies.atsamx7x-hal]
version = "0.4.6"
path = "../../hal"
features = ["same70q21b", "rt", "unproven"]

[features]
log = ["dep:log", "dep:rtt-target"]
log_self = ["log"]
log_device = ["log", "usb-device/log"]
log_hal_usb = ["log", "atsamx7x-hal/usb_log"]

[patch.crates-io]
usb-device = { path = "../../../usb-device" }

[profile.dev]
debug = true
lto = true
